# Generated by Django 6.0.6 on 2026-09-25 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasksapp', '0005_task_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='关卡编号')),
                ('title', models.CharField(max_length=128, verbose_name='关卡名称')),
                ('chain', models.CharField(choices=[('51单片机', '51单片机'), ('物联网', '物联网'), ('电赛', '电赛'), ('无人机', '无人机'), ('嵌入式', '嵌入式'), ('其他', '其他')], default='其他', max_length=32, verbose_name='技能线')),
                ('chapter', models.CharField(choices=[('基础', '基础'), ('进阶', '进阶'), ('大师', '大师')], default='基础', max_length=16, verbose_name='章节')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('score_limit', models.PositiveIntegerField(default=100, verbose_name='满分')),
                ('stars_rule', models.CharField(blank=True, default='', max_length=256, verbose_name='星级规则')),
                ('description', models.TextField(blank=True, default='', verbose_name='关卡说明')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='levels/%Y%m/', verbose_name='封面/徽章图')),
                ('status', models.CharField(choices=[('open', '开放'), ('closed', '已关闭')], default='open', max_length=16, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels_created', to=settings.AUTH_USER_MODEL)),
                ('require_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_levels', to='levels.level', verbose_name='前置关卡')),
            ],
            options={
                'ordering': ['chain', 'chapter', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LevelReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='在职')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_added', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='levels.level')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_reviewer_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('level', 'member')},
            },
        ),
        migrations.CreateModel(
            name='LevelTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('main', '主线'), ('bonus', '加分')], default='main', max_length=16, verbose_name='类型')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_link', to='levels.level')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_links', to='tasksapp.task')),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('level', 'task')},
            },
        ),
        migrations.CreateModel(
            name='PassRecord',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='记录编号')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('passed', '已通过'), ('rejected', '未通过'), ('done', '已通关')], default='pending', max_length=16, verbose_name='状态')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='得分')),
                ('stars', models.PositiveSmallIntegerField(default=0, verbose_name='星级')),
                ('featured', models.BooleanField(default=False, verbose_name='精选')),
                ('first_pass', models.BooleanField(default=False, verbose_name='首通')),
                ('best_score', models.PositiveIntegerField(default=0, verbose_name='最高分')),
                ('best_at', models.DateTimeField(blank=True, null=True, verbose_name='最佳时间')),
                ('media', models.JSONField(blank=True, default=list, verbose_name='完成图/视频')),
                ('note', models.CharField(blank=True, default='', max_length=512, verbose_name='备注')),
                ('opinion', models.TextField(blank=True, default='', verbose_name='审核意见')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_records', to='levels.level')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_passes', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-best_score'],
                'unique_together': {('level', 'member')},
            },
        ),
    ]
