# Generated by Django 6.0.6 on 2026-09-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='activity',
            field=models.BooleanField(default=False, verbose_name='冲刺活动（通关 EXP/积分 ×2）'),
        ),
    ]
