# Generated by Django 6.0.6 on 2026-09-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_level_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='pos_x',
            field=models.FloatField(default=0, verbose_name='画布 X'),
        ),
        migrations.AddField(
            model_name='level',
            name='pos_y',
            field=models.FloatField(default=0, verbose_name='画布 Y'),
        ),
    ]
