# Generated by Django 6.0.6 on 2026-09-23 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='学号/工号')),
                ('role', models.CharField(choices=[('teacher', '指导老师'), ('manager', '负责人'), ('member', '普通成员')], default='member', max_length=16, verbose_name='角色')),
                ('group', models.CharField(blank=True, default='', max_length=64, verbose_name='所属小组')),
                ('direction', models.CharField(blank=True, default='', max_length=128, verbose_name='技术方向')),
                ('contact', models.CharField(blank=True, default='', max_length=128, verbose_name='联系方式')),
                ('active', models.BooleanField(default=True, verbose_name='在籍')),
                ('base_status', models.CharField(choices=[('空闲', '空闲'), ('忙碌', '忙碌'), ('模拟离线', '模拟离线')], default='空闲', max_length=16, verbose_name='工作状态')),
                ('note', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('joined', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='内容')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('private', models.BooleanField(default=False, verbose_name='仅管理可见')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_as_actor', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_about', to='accounts.memberprofile')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
