# Generated by Django 6.0.6 on 2026-09-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('builtin', models.BooleanField(default=False, verbose_name='内置')),
                ('superadmin', models.BooleanField(default=False, verbose_name='系统管理员(免检)')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='权限点集合')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='permission_overrides',
            field=models.JSONField(blank=True, default=dict, verbose_name='权限覆盖'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='members', to='accounts.role', verbose_name='授权角色'),
        ),
    ]
