# Generated by Django 6.0.6 on 2026-09-23 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_builtin_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=128, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='强制改密'),
        ),
        migrations.CreateModel(
            name='LabGroup',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='小组名称')),
                ('capacity', models.PositiveIntegerField(default=20, verbose_name='人数上限')),
                ('note', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='group_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.labgroup', verbose_name='小组'),
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=256, verbose_name='UA')),
                ('success', models.BooleanField(default=True, verbose_name='成功')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
