# Generated by Django 6.0.6 on 2026-09-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_levels_nav_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='level_exp',
            field=models.PositiveIntegerField(default=0, verbose_name='通关经验值 EXP'),
        ),
    ]
