# Generated by Django 6.0.6 on 2026-09-25 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_loginlog_username_alter_loginlog_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='对象编号'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='ref_type',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='对象类型'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['ref_type', 'ref_id'], name='idx_oplog_ref'),
        ),
    ]
