# Generated by Django 6.0.6 on 2026-09-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_grant_new_role_permissions'),
        ('tasksapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_note',
            field=models.TextField(blank=True, default='', verbose_name='完成总结'),
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounts.labgroup', verbose_name='小组任务'),
        ),
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='评分'),
        ),
    ]
