# Generated by Django 6.0.6 on 2026-09-23 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0002_task_completed_at_task_completion_note_task_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='review_opinion',
            field=models.TextField(blank=True, default='', verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='task',
            name='submission',
            field=models.TextField(blank=True, default='', verbose_name='提交内容'),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', '待办'), ('doing', '进行中'), ('submitted', '待审核'), ('done', '已完成')], default='todo', max_length=16, verbose_name='看板列'),
        ),
    ]
