# Generated by Django 6.0.6 on 2026-09-23 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0003_task_review_opinion_task_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_as_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='指定审核人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='实际审核人'),
        ),
    ]
