# Generated by Django 5.2.15 on 2026-06-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0002_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='invoice_image',
            field=models.ImageField(blank=True, upload_to='hardware/invoice/'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='image',
            field=models.ImageField(blank=True, upload_to='hardware/physical/'),
        ),
    ]
