# Generated by Django 5.2.15 on 2026-06-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0004_alter_hardware_image_alter_hardware_invoice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_note',
            field=models.TextField(blank=True),
        ),
    ]
