# Generated by Django 5.2.15 on 2026-06-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0005_task_completion_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
