# Generated by Django 5.2.15 on 2026-06-19 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0006_alter_task_completion_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='approval_status',
            field=models.CharField(default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='hardware',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hardware', to=settings.AUTH_USER_MODEL),
        ),
    ]
