# Generated by Django 5.2.15 on 2026-06-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0007_hardware_approval_note_hardware_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='approval_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
