# Generated by Django 5.2.15 on 2026-06-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0009_hardware_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='purchase_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
