# Generated by Codex on 2026-06-23

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0139_alter_customfieldchoiceset_extra_choices'),
        ('lab_manager', '0011_agentconversation_agentmessage_hardwareimportbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('photo', models.ImageField(upload_to='checkins/photos/', verbose_name='打卡照片')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='经度')),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='定位精度（米）')),
                ('address', models.CharField(blank=True, help_text='可填写实验室、楼宇、房间号或现场说明', max_length=255, verbose_name='地址备注')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_checkins', to=settings.AUTH_USER_MODEL, verbose_name='打卡人')),
            ],
            options={
                'verbose_name': '打卡记录',
                'verbose_name_plural': '打卡记录',
                'ordering': ('-created',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
