# Generated by Codex on 2026-06-23

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0139_alter_customfieldchoiceset_extra_choices'),
        ('lab_manager', '0012_checkinrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberOpenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('path', models.CharField(max_length=500, verbose_name='打开路径')),
                ('page_title', models.CharField(blank=True, max_length=100, verbose_name='页面名称')),
                ('target_type', models.CharField(blank=True, max_length=50, verbose_name='对象类型')),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='对象ID')),
                ('user_agent', models.TextField(blank=True, verbose_name='浏览器标识')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_open_records', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '成员打开记录',
                'verbose_name_plural': '成员打开记录',
                'ordering': ('-created',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
