# Generated by Django 6.0.6 on 2026-06-24 07:09

import lab_manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0014_open_record_add_photo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinrecord',
            name='photo',
            field=models.ImageField(upload_to='checkins/photos/', validators=[lab_manager.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='approval_status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='category',
            field=models.CharField(db_index=True, default='mcu', max_length=30),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hardware/physical/', validators=[lab_manager.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to='hardware/invoice/', validators=[lab_manager.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='status',
            field=models.CharField(db_index=True, default='in_use', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(db_index=True, default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to='task_attachments/', validators=[lab_manager.validators.validate_file_size]),
        ),
    ]
