# Generated by Django 6.0.6 on 2026-06-24 08:41

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0139_alter_customfieldchoiceset_extra_choices'),
        ('lab_manager', '0016_hardware_minimum_stock_hardwareborrowrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('tool_type', models.CharField(db_index=True, max_length=30)),
                ('category', models.CharField(db_index=True, default='data_query', max_length=30)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('parameters_schema', models.JSONField(blank=True, default=dict)),
                ('execution_key', models.CharField(blank=True, default='', max_length=80)),
                ('default_args', models.JSONField(blank=True, default=dict)),
                ('requires_superuser', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': '智能体工具',
                'verbose_name_plural': '智能体工具',
                'ordering': ('sort_order', 'name'),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
