# Generated by Django 6.0.6 on 2026-09-10 16:06

import lab_manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0018_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinrecord',
            name='photo',
            field=models.ImageField(upload_to='checkins/photos/', validators=[lab_manager.validators.validate_file_size, lab_manager.validators.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hardware/physical/', validators=[lab_manager.validators.validate_file_size, lab_manager.validators.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to='hardware/invoice/', validators=[lab_manager.validators.validate_file_size, lab_manager.validators.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='memberopenrecord',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='checkins/photos/', validators=[lab_manager.validators.validate_file_size, lab_manager.validators.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to='task_attachments/', validators=[lab_manager.validators.validate_file_size, lab_manager.validators.validate_attachment_type]),
        ),
    ]
