# Generated by Django 6.0.6 on 2026-09-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0003_add_task_assigned_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrule',
            name='key',
            field=models.CharField(choices=[('task_due', '任务临近截止'), ('task_overdue', '任务已逾期'), ('task_assigned', '任务指派'), ('loan_overdue', '借用已逾期'), ('competition_deadline', '比赛报名截止'), ('competition_start', '比赛开赛提醒'), ('leave_result', '请假审批结果'), ('loan_reviewed', '借用审批结果'), ('loan_issued', '借用发放'), ('asset_repaired', '维修完成'), ('custom', '自定义')], max_length=32, unique=True, verbose_name='规则'),
        ),
    ]
