# Generated by Django 6.0.6 on 2026-09-23 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='比赛编号')),
                ('name', models.CharField(max_length=256, verbose_name='比赛名称')),
                ('organizer', models.CharField(blank=True, default='', max_length=256, verbose_name='主办方')),
                ('level', models.CharField(blank=True, default='', max_length=32, verbose_name='级别')),
                ('category', models.CharField(blank=True, default='', max_length=64, verbose_name='类别')),
                ('registration_start', models.DateTimeField(verbose_name='报名开始')),
                ('registration_end', models.DateTimeField(verbose_name='报名截止')),
                ('start', models.DateTimeField(verbose_name='比赛开始')),
                ('end', models.DateTimeField(verbose_name='比赛结束')),
                ('location', models.CharField(blank=True, default='', max_length=256, verbose_name='地点')),
                ('team_size', models.CharField(blank=True, default='', max_length=64, verbose_name='队伍规模')),
                ('link', models.CharField(blank=True, default='', max_length=512, verbose_name='官方链接')),
                ('summary', models.CharField(blank=True, default='', max_length=1024, verbose_name='简介')),
                ('requirements', models.TextField(blank=True, default='', verbose_name='参赛须知')),
                ('stages', models.JSONField(default=list, verbose_name='流程节点')),
                ('archived', models.BooleanField(default=False, verbose_name='已归档')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
