# Generated by Django 6.0.6 on 2026-09-25 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='布局编号')),
                ('name', models.CharField(default='实验室平面', max_length=64, verbose_name='名称')),
                ('rows', models.IntegerField(default=0, verbose_name='行数')),
                ('cols', models.IntegerField(default=0, verbose_name='列数')),
                ('grid', models.JSONField(blank=True, default=list, verbose_name='格子矩阵')),
                ('labels', models.JSONField(blank=True, default=dict, verbose_name='座位编号')),
                ('owners', models.JSONField(blank=True, default=dict, verbose_name='默认归属')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='MemberCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts', models.JSONField(blank=True, default=dict, verbose_name='部件')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_character', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeatChatCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(verbose_name='上次已读时间')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_chat_cursor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeatMessage',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='气泡编号')),
                ('text', models.CharField(max_length=50, verbose_name='内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubbles', to='seats.seatlayout')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_bubbles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SeatPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='行')),
                ('col', models.IntegerField(verbose_name='列')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='seats.seatlayout')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_presence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_key', models.CharField(choices=[('work', '在工位'), ('debug', '调试中'), ('meeting', '开会'), ('rest', '休息'), ('out', '实验室外'), ('custom', '自定义')], default='work', max_length=16, verbose_name='状态')),
                ('text', models.CharField(blank=True, default='', max_length=30, verbose_name='状态文字')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeatChat',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='消息编号')),
                ('text', models.CharField(max_length=200, verbose_name='内容')),
                ('active', models.BooleanField(default=True, verbose_name='有效')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='seats_seatc_created_ff2357_idx')],
            },
        ),
    ]
