# Generated by Django 6.0.6 on 2026-09-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_checkinrecord_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinrecord',
            name='signout_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签退时间'),
        ),
    ]
