# Generated by Django 6.0.6 on 2026-09-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0003_checkinrecord_signout_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinrecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
    ]
