# Generated by Django 6.0.6 on 2026-09-23 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_memberprofile_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='编号')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('scope', models.CharField(choices=[('all', '全体成员'), ('group', '指定小组'), ('members', '指定成员')], default='all', max_length=16, verbose_name='范围')),
                ('member_ids', models.JSONField(blank=True, default=list, verbose_name='指定成员')),
                ('active', models.BooleanField(default=True, verbose_name='有效')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='accounts.labgroup')),
            ],
            options={
                'ordering': ['-pinned', '-created'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notify.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
