# Generated by Django 6.0.6 on 2026-09-23 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_newsitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='编号')),
                ('kind', models.CharField(choices=[('loan_apply', '借用申请'), ('loan_reviewed', '借用审批结果'), ('loan_issued', '借用发放'), ('loan_return_requested', '归还申请'), ('loan_returned', '归还验收'), ('loan_overdue', '借用逾期'), ('leave_apply', '请假申请'), ('leave_reviewed', '请假审批结果'), ('task_assigned', '任务指派'), ('task_completed', '任务完成'), ('task_scored', '任务评分'), ('task_due', '任务到期'), ('competition_published', '新比赛发布'), ('competition_deadline', '报名截止'), ('competition_start', '开赛提醒'), ('announcement_published', '新公告'), ('asset_repaired', '维修完成'), ('points_changed', '积分变动'), ('member_joined', '成员加入')], max_length=32, verbose_name='类型')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('body', models.TextField(blank=True, default='', verbose_name='正文')),
                ('ref_type', models.CharField(blank=True, default='', max_length=32, verbose_name='引用类型')),
                ('ref_id', models.CharField(blank=True, default='', max_length=64, verbose_name='引用编号')),
                ('link', models.CharField(blank=True, default='', max_length=64, verbose_name='前端路由')),
                ('read', models.BooleanField(default=False, verbose_name='已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'kind', 'ref_type', 'ref_id'), name='uniq_notification_ref')],
            },
        ),
    ]
