# Generated by Django 6.0.6 on 2026-09-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('loan_apply', '借用申请'), ('loan_reviewed', '借用审批结果'), ('loan_issued', '借用发放'), ('loan_return_requested', '归还申请'), ('loan_returned', '归还验收'), ('loan_overdue', '借用逾期'), ('leave_apply', '请假申请'), ('leave_reviewed', '请假审批结果'), ('task_assigned', '任务指派'), ('task_completed', '任务完成'), ('task_scored', '任务评分'), ('task_due', '任务到期'), ('task_submitted', '任务待审核'), ('task_reviewed', '任务审核通过'), ('task_rejected', '任务被退回'), ('competition_published', '新比赛发布'), ('competition_deadline', '报名截止'), ('competition_start', '开赛提醒'), ('announcement_published', '新公告'), ('asset_repaired', '维修完成'), ('points_changed', '积分变动'), ('member_joined', '成员加入')], max_length=32, verbose_name='类型'),
        ),
    ]
