# Generated by Django 6.0.6 on 2026-09-24 10:58

from django.db import migrations, models

from apps.homepage.defaults import IMAGE_DEFAULTS, TEXT_DEFAULTS


def seed(apps, schema_editor):
    HomePageText = apps.get_model('homepage', 'HomePageText')
    HomePageImage = apps.get_model('homepage', 'HomePageImage')
    for key, (label, value) in TEXT_DEFAULTS.items():
        HomePageText.objects.update_or_create(pk=key, defaults={'label': label, 'value': value})
    for key, (label, seed_ref, alt) in IMAGE_DEFAULTS.items():
        HomePageImage.objects.update_or_create(pk=key, defaults={'label': label, 'seed': seed_ref, 'alt': alt})


def unseed(apps, schema_editor):
    apps.get_model('homepage', 'HomePageText').objects.all().delete()
    apps.get_model('homepage', 'HomePageImage').objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='标识')),
                ('label', models.CharField(default='', max_length=128, verbose_name='后台表单标题')),
                ('alt', models.CharField(blank=True, default='', max_length=256, verbose_name='图片 alt')),
                ('seed', models.CharField(default='', max_length=256, verbose_name='默认引用')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/%Y%m/', verbose_name='上传图片')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='HomePageText',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='标识')),
                ('label', models.CharField(default='', max_length=128, verbose_name='后台表单标题')),
                ('value', models.TextField(blank=True, default='', verbose_name='文案')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.RunPython(seed, unseed),
    ]
