# Generated by Django 6.0.6 on 2026-09-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageimage',
            name='kind',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video')], default='image', max_length=16, verbose_name='媒体类型'),
        ),
        migrations.AddField(
            model_name='homepageimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='homepage/%Y%m/', verbose_name='上传视频'),
        ),
    ]
