# Generated by Django 6.0.6 on 2026-09-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_homepageimage_kind_homepageimage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageimage',
            name='scale',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='显示缩放'),
        ),
    ]
