# Generated by Django 6.0.6 on 2026-09-23 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True, verbose_name='规则键')),
                ('label', models.CharField(max_length=64, verbose_name='规则名称')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='单位分值')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('builtin', models.BooleanField(default=True, verbose_name='内置')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PointRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(max_length=32, verbose_name='规则')),
                ('points', models.IntegerField(default=0, verbose_name='分值')),
                ('ref_type', models.CharField(blank=True, default='', max_length=32, verbose_name='关联类型')),
                ('ref_id', models.CharField(blank=True, default='', max_length=64, verbose_name='关联编号')),
                ('reason', models.CharField(blank=True, default='', max_length=256, verbose_name='说明')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('user', 'rule_key', 'ref_type', 'ref_id'), name='uniq_point_award')],
            },
        ),
    ]
