# Generated by Django 6.0.6 on 2026-09-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_seed_level_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrule',
            name='points',
            field=models.IntegerField(default=0, verbose_name='单位分值'),
        ),
    ]
