'use strict';
function seed() {
  const memberData = [
    ['m1', '陈明远', 'teacher', '导师组', '嵌入式系统架构', '空闲', 'teacher'],
    ['m2', '林知远', 'manager', '系统研发组', '嵌入式 Linux', '空闲', 'manager'],
    ['m3', '张子涵', 'member', '硬件研发组', 'STM32 / 电路设计', '忙碌', 'member'],
    ['m4', '李沐阳', 'member', '物联网组', '无线通信 / IoT', '空闲', 'limuyang'],
    ['m5', '王雨桐', 'member', '系统研发组', '机器人控制', '空闲', 'wangyutong'],
    ['m6', '赵一鸣', 'member', '硬件研发组', '传感器融合', '忙碌', 'zhaoyiming'],
    ['m7', '陈思远', 'member', '物联网组', '低功耗通信', '空闲', 'chensiyuan'],
    ['m8', '周可欣', 'member', '系统研发组', '边缘计算', '离线', 'zhoukexin'],
  ];
  const members = memberData.map((m, i) => ({
    id: m[0],
    name: m[1],
    role: m[2],
    group: m[3],
    direction: m[4],
    baseStatus: m[5],
    username: m[6],
    number: i < 2 ? `T202600${i + 1}` : `202400${i + 1}`,
    contact: `${m[6]}@lab.example`,
    joined: date(-180 - i * 8),
    note: m[5] === '忙碌' ? '项目调试中' : '',
    updated: date(-1, 17),
    active: true,
  }));
  const specs = [
    ['STM32F407 开发板', 'STM32F407ZGT6', '开发板', 'STMicroelectronics', '3.3V · UART / SPI / I²C', 'A-01'],
    ['ESP32 开发板', 'ESP32-WROOM-32', '开发板', 'Espressif', '3.3V · Wi-Fi / BLE', 'A-02'],
    ['树莓派 4B', 'Raspberry Pi 4B / 4GB', '单板计算机', 'Raspberry Pi', '5V · USB / HDMI / GPIO', 'A-03'],
    ['DHT22 温湿度传感器', 'DHT22 / AM2302', '传感器', 'Aosong', '3.3–5V · 单总线', 'B-01'],
    ['MPU6050 六轴传感器', 'MPU-6050', '传感器', 'TDK InvenSense', '3.3V · I²C', 'B-02'],
    ['LoRa 无线模块', 'SX1278 / 433MHz', '通信模块', 'Semtech', '3.3V · SPI', 'C-01'],
    ['ST-Link 调试器', 'ST-Link V2', '调试工具', 'STMicroelectronics', '3.3V · SWD / JTAG', 'D-01'],
    ['SG90 微型舵机', 'SG90 / 9g', '执行器', 'TowerPro', '5V · PWM', 'E-01'],
    ['Arduino Uno', 'UNO R3', '开发板', 'Arduino', '5V · UART / SPI', 'A-04'],
    ['USB 转串口模块', 'CH340G', '调试工具', 'WCH', '3.3/5V · UART', 'D-02'],
    ['超声波测距模块', 'HC-SR04', '传感器', '通用', '5V · GPIO', 'B-03'],
    ['蓝牙串口模块', 'HC-05', '通信模块', '通用', '3.3V · UART', 'C-02'],
    ['N20 减速电机', 'N20 / 100RPM', '执行器', '通用', '6V · 直流', 'E-02'],
  ];
  const assets = Array.from({ length: 18 }, (_, i) => {
    const s = specs[i < 13 ? i : [0, 1, 4, 6, 5][i - 13]];
    return {
      id: `EM-${String(i + 1).padStart(3, '0')}`,
      name: s[0],
      model: s[1],
      category: s[2],
      vendor: s[3],
      spec: s[4],
      location: `器材柜 ${s[5]}`,
      status: i === 7 || i === 10 ? '维修中' : i === 12 ? '已报废' : '空闲',
      created: date(-90 - i),
      note: i === 7 ? '齿轮异常，等待更换' : i === 10 ? '测距不稳定，待检修' : '',
      datasheet: '',
    };
  });
  const loans = [
    {
      id: 'BR-2026-001',
      memberId: 'm3',
      assetIds: ['EM-001', 'EM-007'],
      purpose: '智能小车主控调试',
      project: '智能巡检小车',
      status: '使用中',
      created: date(-3),
      issued: date(-2),
      due: date(3),
      reviewer: 'm2',
      opinion: '同意，用后归还原位',
    },
    {
      id: 'BR-2026-002',
      memberId: 'm4',
      assetIds: ['EM-002'],
      purpose: '环境监测节点联调',
      project: '智慧实验室',
      status: '使用中',
      created: date(-4),
      issued: date(-3),
      due: date(5),
      reviewer: 'm2',
    },
    {
      id: 'BR-2026-003',
      memberId: 'm6',
      assetIds: ['EM-005'],
      purpose: '姿态解算测试',
      project: '两轮自平衡车',
      status: '使用中',
      created: date(-8),
      issued: date(-7),
      due: date(-1),
      reviewer: 'm2',
    },
    {
      id: 'BR-2026-004',
      memberId: 'm8',
      assetIds: ['EM-003'],
      purpose: '边缘图像推理',
      project: '视觉识别',
      status: '待确认归还',
      created: date(-5),
      issued: date(-4),
      due: date(2),
      reviewer: 'm1',
      returnRequested: date(-1, 17),
    },
    {
      id: 'BR-2026-005',
      memberId: 'm3',
      assetIds: ['EM-006'],
      purpose: '无线传输距离测试',
      project: '智能巡检小车',
      status: '待审批',
      created: date(-1, 16),
      due: date(7),
    },
    {
      id: 'BR-2026-006',
      memberId: 'm4',
      assetIds: ['EM-004'],
      purpose: '温湿度采样',
      project: '智慧实验室',
      status: '已归还',
      created: date(-12),
      issued: date(-11),
      due: date(-5),
      returned: date(-6),
      reviewer: 'm2',
    },
  ];
  const leaves = [
    {
      id: 'LV-001',
      memberId: 'm5',
      start: date(-1),
      end: date(2, 18),
      reason: '个人事务',
      status: '已通过',
      created: date(-3),
      reviewer: 'm2',
      opinion: '同意',
      reviewed: date(-2),
    },
    { id: 'LV-002', memberId: 'm7', start: date(1), end: date(3, 18), reason: '参加校外技术交流', status: '待审批', created: date(-1, 15) },
  ];
  return {
    version: 1,
    competitions: seedCompetitions(),
    members,
    assets,
    loans,
    leaves,
    maintenance: [{ id: 'MT-001', assetId: 'EM-008', description: '舵机齿轮异常', status: '维修中', created: date(-2), actor: 'm2' }],
    logs: [
      { id: 'LOG-1', actor: '林知远', text: '确认归还 DHT22 温湿度传感器', at: date(-6), memberId: 'm4' },
      { id: 'LOG-2', actor: '陈明远', text: '发放树莓派 4B 给周可欣', at: date(-4), memberId: 'm8' },
      { id: 'LOG-3', actor: '张子涵', text: '申请借用 LoRa 无线模块', at: date(-1, 17), memberId: 'm3' },
      { id: 'LOG-4', actor: '周可欣', text: '提交树莓派 4B 归还申请', at: date(-1, 17), memberId: 'm8' },
    ],
  };
}
// 比赛日期均为相对当前日期生成的演示安排，不代表真实官方赛事日程。
function seedCompetitions() {
  return [
    {
      id: 'COMP-001',
      name: '嵌入式系统创新设计赛',
      organizer: '实验室 / 校内训练赛（示例）',
      level: '校级',
      category: '嵌入式设计',
      registrationStart: date(-5, 9),
      registrationEnd: date(8, 18),
      start: date(21, 9),
      end: date(22, 18),
      location: '工程实践中心 A301',
      ownerId: 'm2',
      teamSize: '2–4 人 / 队',
      link: '',
      summary: '围绕智能感知与控制，完成一套可演示的嵌入式系统作品。',
      requirements:
        '参赛对象：实验室在籍成员，可跨小组组队。\n组队要求：每队 2–4 人，指定一位队长负责报名与材料提交。\n提交材料：项目说明书、原理图、核心代码及演示视频。\n作品要求：说明使用的开源组件，保证作品和文档来源真实。\n现场须知：自备开发板与调试线，提前 30 分钟到场完成设备检查。',
      stages: [
        { title: '报名与组队', at: date(8, 18), description: '报名截止前确认队员、队长和项目方向。' },
        { title: '方案评审', at: date(12, 14), description: '提交系统框图、硬件选型和开发计划。' },
        { title: '作品提交', at: date(19, 18), description: '提交代码、技术文档和演示视频。' },
        { title: '现场答辩', at: date(21, 9), description: '作品演示 8 分钟，评委提问 5 分钟。' },
        { title: '结果公布', at: date(22, 18), description: '汇总评分，组织赛后技术复盘。' },
      ],
      archived: false,
      created: date(-7),
    },
    {
      id: 'COMP-002',
      name: '智能小车算法挑战赛',
      organizer: '具身智能实验室（示例）',
      level: '实验室',
      category: '机器人与控制',
      registrationStart: date(-14, 9),
      registrationEnd: date(-3, 18),
      start: date(4, 9),
      end: date(4, 18),
      location: '实验楼一层 · 测试场地',
      ownerId: 'm1',
      teamSize: '1–3 人 / 队',
      link: '',
      summary: '在指定赛道完成循迹、避障与定点停车，综合考察控制算法与系统稳定性。',
      requirements:
        '使用低压直流供电，测试前检查电池和接线。\n每支队伍有两次正式运行机会，按较好成绩计分。\n比赛过程中不得人工干预车辆行驶。\n请提前准备备用电池、调试线和现场演示说明。',
      stages: [
        { title: '报名截止', at: date(-3, 18), description: '提交成员名单及车辆配置。' },
        { title: '赛道试跑', at: date(2, 14), description: '熟悉赛道，完成安全检查。' },
        { title: '正式比赛', at: date(4, 9), description: '按抽签顺序进行计时挑战。' },
        { title: '成绩公布', at: date(4, 18), description: '统计成绩并交流算法实现。' },
      ],
      archived: false,
      created: date(-16),
    },
    {
      id: 'COMP-003',
      name: '物联网应用开发训练赛',
      organizer: '物联网兴趣小组（示例）',
      level: '实验室',
      category: '物联网应用',
      registrationStart: date(10, 9),
      registrationEnd: date(25, 18),
      start: date(40, 9),
      end: date(41, 17),
      location: '线上提交 / 实验室答辩',
      ownerId: 'm2',
      teamSize: '2–5 人 / 队',
      link: '',
      summary: '设计从传感器采集、无线通信到数据可视化的完整物联网应用。',
      requirements:
        '以 ESP32 或同类控制器为核心完成原型。\n演示数据可使用模拟数据，但须在作品中明确标注。\n提交部署说明、依赖清单和设备接线图。\n演示账号中不得包含个人或生产环境密钥。',
      stages: [
        { title: '开放报名', at: date(10, 9), description: '组建队伍并选择应用主题。' },
        { title: '报名截止', at: date(25, 18), description: '确认队伍名单和项目计划。' },
        { title: '线上提交', at: date(38, 18), description: '提交可运行的作品与说明。' },
        { title: '作品答辩', at: date(40, 9), description: '完成作品讲解与实际演示。' },
      ],
      archived: false,
      created: date(-1),
    },
  ];
}
