# Generated by Django 6.0.6 on 2026-09-23 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='请假单号')),
                ('start', models.DateTimeField(verbose_name='开始时间')),
                ('end', models.DateTimeField(verbose_name='结束时间')),
                ('reason', models.CharField(blank=True, default='', max_length=512, verbose_name='原因')),
                ('status', models.CharField(choices=[('待审批', '待审批'), ('已批准', '已批准'), ('已拒绝', '已拒绝'), ('已撤销', '已撤销')], default='待审批', max_length=16, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed', models.DateTimeField(blank=True, null=True)),
                ('opinion', models.CharField(blank=True, default='', max_length=256, verbose_name='审批意见')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
