# Generated by Django 6.0.6 on 2026-09-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leave_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('待审批', '待审批'), ('已批准', '已批准'), ('已拒绝', '已拒绝'), ('已撤销', '已撤销'), ('已销假', '已销假')], default='待审批', max_length=16, verbose_name='状态'),
        ),
    ]
