# Generated by Django 6.0.6 on 2026-09-23 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='资产编号')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('model', models.CharField(blank=True, default='', max_length=128, verbose_name='型号')),
                ('category', models.CharField(blank=True, default='', max_length=64, verbose_name='类别')),
                ('vendor', models.CharField(blank=True, default='', max_length=128, verbose_name='供应商')),
                ('spec', models.CharField(blank=True, default='', max_length=256, verbose_name='规格')),
                ('location', models.CharField(blank=True, default='', max_length=128, verbose_name='位置')),
                ('status', models.CharField(choices=[('空闲', '空闲'), ('使用中', '使用中'), ('维修中', '维修中'), ('报废', '报废')], default='空闲', max_length=16, verbose_name='状态')),
                ('note', models.CharField(blank=True, default='', max_length=512, verbose_name='备注')),
                ('datasheet', models.CharField(blank=True, default='', max_length=512, verbose_name='资料链接')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='借用单号')),
                ('purpose', models.CharField(blank=True, default='', max_length=256, verbose_name='用途')),
                ('project', models.CharField(blank=True, default='', max_length=128, verbose_name='关联项目')),
                ('status', models.CharField(choices=[('待审批', '待审批'), ('已批准', '已批准'), ('已拒绝', '已拒绝'), ('已取消', '已取消'), ('使用中', '使用中'), ('归还申请中', '归还申请中'), ('已完成', '已完成')], default='待审批', max_length=16, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('due', models.DateTimeField(verbose_name='预计归还')),
                ('reviewed', models.DateTimeField(blank=True, null=True)),
                ('opinion', models.CharField(blank=True, default='', max_length=256, verbose_name='审批意见')),
                ('issued', models.DateTimeField(blank=True, null=True)),
                ('return_requested', models.DateTimeField(blank=True, null=True)),
                ('received', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=512, verbose_name='验收备注')),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_issued', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_items', to='inventory.asset')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='维修单号')),
                ('description', models.CharField(max_length=512, verbose_name='问题描述')),
                ('status', models.CharField(default='维修中', max_length=16, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='inventory.asset')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
