# Generated by Django 6.0.6 on 2026-09-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/%Y%m/', verbose_name='模块图片'),
        ),
    ]
