# Generated by Django 6.0.6 on 2026-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_loan_updated_maintenance_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanitem',
            name='damaged',
            field=models.BooleanField(default=False, verbose_name='验收损坏'),
        ),
    ]
